### ISSUE TITLE
Typographic/TeX issues

### ISSUE THREAD

**Issue by EdwinOdesseiron** [physicsnerd/calculus-notes#3]
General: 

 - There is no reason not to use the `hyperref` package to make the TOC into active links (and all references within the document, too, although currently there aren't any).

 - The "resources" section should be a bibliography in the standard LaTeX sense, not its own section

 - Your quotation marks are "wrong" - opening quotation marks should be inverted, which is done by using a double backtick instead of the quotation mark (most editors should have an option to do this intelligently for you).

 - The `d` in the derivatives/integral should be upright `\mathrm{d}`, since it is not a variable.

 - Within displaystyle (i.e. displayed equation as in `\begin{equation}...end{equation}`) the `\limits` is completely unnecessary and can safely be omitted

Specific:

 - Line 42 ff.: The functions and variables should be inline TeX, not standard text.

 - Line 68: Riemann, not Rieman

**Comment by DanielSank** [comment]
+1 for hyperref, although beware it can be a PITA to get the options right in some cases. If you get stuck, remember that there's a really good TeX/LaTeX Stack Exchange.

To be explicit, the way you do quotes in TeX is like this: `blah blah ``quoted stuff'' blah blah`.

FWIW I don't use the upright `d` in my own stuff. If you're going to use it, I'd recommend making a macro for it so you don't have to type `\mathrm` every single time.

**Comment by physicsnerd** [comment]
I finished the specific edits, I'll come back and do the more general edits later.

**Comment by physicsnerd** [comment]
the branch 7-formal def has the hyperref package set up for the table of contents.
