### ISSUE TITLE
notes.tex could be split into smaller files

### ISSUE THREAD

**Issue by DanielSank** [physicsnerd/calculus-notes#4]
Using `\input{subfile}`, you can break up a TeX project into smaller bits, which makes editing and general maintenance easier. For a very in-depth look at how to manage TeX projects in a modular way, perhaps see [this blog post](https://danielsank.github.io/tex_modularity/) by yours truly.

I wouldn't recommend using all the advanced stuff in that post, but at least there are complete working examples showing various levels of sophistication. You could start with just the first level.

**Comment by physicsnerd** [comment]
I'm not sure I did it correctly - does it look alright?

Also, how do I create folders, one for the pictures and one for the tex files?

**Comment by DanielSank** [comment]
> I'm not sure I did it correctly - does it look alright?

Definitely a improvement!

> Also, how do I create folders, one for the pictures and one for the tex files?

To create a folder, in repository on your computer, do this

```
$ mkdir images
```

That makes a new directory called images. Then you can move your files there like this

```
$ git mv my_image.png images
```

The `git mv` command is nice because it tells git that the "new" file `/images/my_image.png` is what used to be `/my_image.png`. This just makes the diff and commit history easier to understand. Once you've done the move, you just `git add` and `git commit` like usual.

Does that answer your question?
